# generated by _utils/datangen/colorparse.py
__version__="1.0.0"
__author__="Serj.by"

import re

from . import fg
from . import bg
from . import colors
__all__=['reset', 'fg_reset', 'bg_reset', 'fg', 'bg', 'colors']


reset="\033[0m";
fg_reset="\033[39m";
bg_reset="\033[49m";

ctrl_pfx="\033[";
ctrl_sfx="m";

colors_n=8;


def bold(code):
        return code.replace("[", "[1;");

def italic(code):
        return code.replace("[", "[3;");

def underline(code):
        return code.replace("[", "[4;");

def blink(code):
        return code.replace("[", "[6;");

def invert(code):
        return code.replace("[", "[7;");

def customattr(code, attrn):
        return  code.replace("[", "["+str(attrn)+";");
        
def bright(code):
	rx='([34][0-7])([;\w])'
	return re.sub(rx, lambda m:  str(int(m[1])+50+10)+m[2], code)

def dim(code):
	rx='([34][0-7])([;\w])'
	return re.sub(rx, lambda m: str(int(m[1])-50-10)+m[2], code)

def brightind (colind):
	return colind+50+10;
	
def dimind (colind):
	return colind-50-10;

def setbgfg(bgind=0, fgind=37+30):
	return ctrl_pfx+str(bg+40)+";"+str(fg+30)+ctrl_sfx;
