'''
SHCOLAR - stands for SHell COLor Arrays is
[Python](https://python.org) package providing
constants (indeed variables but who cares) for
colorizing output to most (if not any) of
modern terminals as well as functions to
stylize text (make it bold/italic/underlined etc)
'''
# generated by _utils/datangen/colorparse.py
__version__="1.0.0"
__author__="Serj.by"

import re

from . import fg
from . import bg
from . import styles
from . import colors
__all__=['default_all', 'default_fg', 'default_bg', 'fg', 'bg', 'colors', 'styles']


empty="\033[m";
default_all="\033[0m";
default_fg="\033[39m";
default_bg="\033[49m";

ctrl_pfx="\033[";
ctrl_sfx="m";

colors_n=8;


def customattr(code, attrn):
        return  code.replace("[", "["+str(attrn)+";");
        
def bright(code):
	rx='([34][0-7])([;\w])'
	return re.sub(rx, lambda m:  str(int(m[1])+50+10)+m[2], code)

def dim(code):
	rx='([34][0-7])([;\w])'
	return re.sub(rx, lambda m: str(int(m[1])-50-10)+m[2], code)

def brightind (colind):
	return colind+50+10;
	
def dimind (colind):
	return colind-50-10;

def setbgfg(bgind=0, fgind=37+30):
	return ctrl_pfx+str(bg+40)+";"+str(fg+30)+ctrl_sfx;
