# generated by _utils/datangen/colorparse.py
__version__="1.0.0"
__author__="Serj.by"

from . import fg
from . import bg
from . import colors
__all__=['reset', 'fg_reset', 'bg_reset', 'fg', 'bg', 'colors']


reset="\033[0m";
fg_reset="\033[39m";
bg_reset="\033[49m";

ctrl_pfx="\033[";
ctrl_sfx="m";

colors_n=8;


def bold(col):
        return col.replace("[", "[1;");

def italic(col):
        return col.replace("[", "[3;");

def underline(col):
        return col.replace("[", "[4;");

def blink(col):
        return col.replace("[", "[6;");

def invert(col):
        return col.replace("[", "[7;");

def customattr(col, attrn):
        return  col.replace("[", "["+str(attrn)+";");

def brightind (colind):
	return colind+50+10;
	
def dimind (colind):
	return colind-50-10;

def setbgfg(bg=0, fg=37+30):
	return ctrl_pfx+str(bg+40)+";"+str(fg+30)+ctrl_sfx;
